import Navbar from "../../components/Navbar";

export const metadata = { title: "Terms of Service — ResumeAI Hub" };

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <div className="legal-page">
        <h1>Terms of Service</h1>
        <p className="legal-date">Last updated: {new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}</p>

        <section>
          <h2>1. Acceptance of Terms</h2>
          <p>By accessing or using ResumeAI Hub ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
        </section>

        <section>
          <h2>2. Description of Service</h2>
          <p>ResumeAI Hub provides AI-powered resume analysis tools. The Service analyzes resumes against job descriptions and provides feedback, scores, and suggestions. Results are generated by AI and are for informational purposes only.</p>
        </section>

        <section>
          <h2>3. No Guarantee of Results</h2>
          <p>ResumeAI Hub does not guarantee that using the Service will result in job interviews, employment offers, or any specific career outcome. AI-generated feedback is advisory only and may not reflect the views of any specific employer or recruiter.</p>
        </section>

        <section>
          <h2>4. Acceptable Use</h2>
          <p>You agree not to:</p>
          <ul>
            <li>Use the Service for any unlawful purpose</li>
            <li>Attempt to circumvent usage limits or access controls</li>
            <li>Submit false, misleading, or harmful content</li>
            <li>Reverse engineer or attempt to extract the underlying AI models</li>
            <li>Use automated tools to make bulk requests</li>
          </ul>
        </section>

        <section>
          <h2>5. Account Responsibility</h2>
          <p>You are responsible for maintaining the security of your account credentials. You are responsible for all activity that occurs under your account. Notify us immediately of any unauthorized use.</p>
        </section>

        <section>
          <h2>6. Free Tier Limitations</h2>
          <p>Free accounts are limited to 2 lifetime analyses. We reserve the right to modify free tier limits at any time with reasonable notice.</p>
        </section>

        <section>
          <h2>7. Intellectual Property</h2>
          <p>The Service, including its design, code, and AI outputs, is owned by ResumeAI Hub. You retain ownership of the resume content you submit.</p>
        </section>

        <section>
          <h2>8. Disclaimer of Warranties</h2>
          <p>The Service is provided "as is" without warranties of any kind. We do not warrant that the Service will be uninterrupted, error-free, or that AI outputs will be accurate or complete.</p>
        </section>

        <section>
          <h2>9. Limitation of Liability</h2>
          <p>To the maximum extent permitted by law, ResumeAI Hub shall not be liable for any indirect, incidental, or consequential damages arising from your use of the Service.</p>
        </section>

        <section>
          <h2>10. Changes to Terms</h2>
          <p>We may update these Terms at any time. Continued use of the Service after changes constitutes acceptance of the new Terms.</p>
        </section>

        <section>
          <h2>11. Contact</h2>
          <p>Questions about these Terms? Contact us at support@resumeaihub.com.</p>
        </section>
      </div>
    </>
  );
}
